language: python
python:
  - "3.6"

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

install:
  - sudo apt-get install -y pdf2svg
  - (cd travis && source ./install_texlive.sh)

before_script:
  - export PATH=/tmp/texlive/bin/x86_64-linux:$PATH

script:
  - make all

before_deploy:
  - mkdir _build
  - cp index.html _build/
  - cp 3d/hisparc_3d.stl _build/
  - cp animated/*.gif _build/
  - cp favicon/*.ico _build/
  - cp */*.pdf _build/
  - cp */*.svg _build/
  - touch _build/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _build
  email: beheer@hisparc.nl
  name: HiSPARC-Bot
  on:
    branch: travis
